### ISSUE TITLE
PHP Exception in version 6.4.0.0

### ISSUE THREAD

**Issue by digitalwert-developer** [FriendsOfShopware/FroshPlatformThumbnailProcessor#16]
Hi,

I get an error on the start page while using your Plugin FroshPlatformThumbnailProcessor. Seems to be an issue with Cart Icons or something like that. Have you checked the compability with Shopware 6.4.0.0?

Argument 2 passed to Shopware\Core\Content\Media\Thumbnail\ThumbnailService::__construct() must implement interface League\Flysystem\FilesystemInterface, instance of Shopware\Core\Content\Media\DataAbstractionLayer\MediaThumbnailRepositoryDecorator given

Thanks and best regards!

**Comment by tinect** [comment]
Hey @digitalwert-developer 
should be fixed in the new release.

**Comment by digitalwert-developer** [comment]
Hi @tinect,

thanks for your fast response! It's now working with 6.4.

But we still have a problem. 
Images, that I add in the shopping experiences are not showing. 
Do you have an idea why?

**Comment by tinect** [comment]
Did you use the release of this plugin? 🤔 
There should be JS file in `src/Resources/app/storefront/dist/storefront/js/`

**Comment by digitalwert-developer** [comment]
We did the update in the admin area. The error with 6.4 disappeared, so it should be the newest version.
In the folder you mentioned, there is a JS file called frosh-platform-thumbnail-processor.js.

We also tried to use https://github.com/FriendsOfShopware/FroshPlatformThumbnailProcessorImgProxy, but it didn't help.

**Comment by tinect** [comment]
I made a new release on friday which cleans up the code, but should not impact any visibility. Could you please update and verify again images in storefront are shown?

**Comment by digitalwert-developer** [comment]
Oh I'm sorry, it had nothing to do with your app/plugin.

An element of the shopping experiences had an error, so I deleted that one. Now it's working!

Thanks for your great support!

**Comment by tinect** [comment]
No problem, you're welcome :-)
